### PR TITLE
Make stamp factory caching optional and external

### PR DESCRIPTION
**Pull request by troutowicz**
Fixes issue #24.

Docs still need to be updated to explain what the `cacheStamp` method is and when it might be used.

When designing components as factories, `cacheStamp` can be used like:

``` js
import stampit from 'react-stampit';
import { cacheStamp } from 'react-stampit/utils/cache';

export default React => cacheStamp(
  stampit(React, {
    displayName: 'Component',

    // description object props
  })
);
```

`displayName` is still used as the unique identifier. If `displayName` is not provided it will be set to 'ReactStamp'. If `cacheStamp` is called with a component having a `displayName` of 'ReactStamp', it will still get cached.

cc @ericelliott @BerkeleyTrue

### CODE REVIEW

**Comment by ericelliott** [comment]
> If cacheStamp is called with a component having a displayName of 'ReactStamp', it will still get cached.

This is confusing. How can you safely cache the default `displayName`? Won't various stamps collide if you forget a unique `displayName`?

**Comment by troutowicz** [comment]
They would collide, absolutely. Since this PR is making `cacheStamp` optional and usable in user land, I thought it best to leave it up to the developer's discretion on what is passed to `cacheStamp`. If they want to cache a stamp without a `displayName`, knowing in advance what the consequences of that may be, I think that is acceptable. If not, we can add back the check to ignore `displayName` 'ReactStamp'.

**Comment by BerkeleyTrue** [comment]
>  it best to leave it up to the developer's discretion on what is passed to cacheStamp

Why not let the user provide id's instead?

**Comment by troutowicz** [comment]
Something like this?

``` js
cacheStamp(stamp, uniqueID);
```

And if `uniqueID` is not passed, just return the stamp without caching?

**Comment by troutowicz** [comment]
I think I have a couple issues with this PR I need to address. With the way things are atm, `cacheStamp` will repeatedly update the internal cache every time a stamp factory is used. I think `cacheStamp` should be checking the cache first, then caching if needed.

Once that is changed, and the above unique ID suggestion is implemented, things might work well.

**Comment by BerkeleyTrue** [comment]
> cacheStamp(stamp, uniqueID);

Yeah that looks good.

**Comment by ericelliott** [comment]
Sounds much better. :+1:

**Comment by troutowicz** [comment]
The `cacheStamp` function now accepts a unique id as a second parameter. I have also updated the example in the README.

With these changes, caching is now completely decoupled from react-stampit and is an optional utility.

``` js
import stampit from 'react-stampit';
import { isStampCached, getCachedStamp, cacheStamp } from 'react-stampit/utils/cache';

export default React => {
  if (isStampCached(1)) return getCachedStamp(1);

  return cacheStamp(
    stampit(React, {
      // description object props
    }), 1
  );
};
```

There should probably be a function in the cache module to generate a random unique id. Not doing so would make using published stamp factory components challenging as the developer would not know what unique ids might have been used for caching.

**Comment by troutowicz** [comment]
Here is another implementation.

``` js
import stampit from 'react-stampit';
import * as cache from 'react-stampit/utils/cache';

const id = cache.genID();

export default React => {
  return cache.find(id) || cache.save(
    stampit(React, {
      // description object props
    }), id
  );
};
```

**Comment by JosephClay** [comment]
I like option 2, but can it be `cache.uniqueId()` to match [other incrementing int generators?](https://lodash.com/docs#uniqueId)

Edit: Just noticed it's not an incrementing int. Is there a reason why that couldn't be simplified?

**Comment by troutowicz** [comment]
Good idea, updated.

**Comment by ericelliott** [comment]
I guess that a number as a `displayName` should provide some strong incentive to always include a `displayName` so you don't have to look at meaningless numbers...

**Comment by troutowicz** [comment]
@ericelliott Do you mean use something like lodash's `uniqueId` method to set the `displayName` of components that do not have `displayName` set? Instead of the current default, 'ReactStamp'? I'd be fine with that.

So, for this PR, the final API for a fully functional factory component is:

``` js
import stampit from 'react-stampit';
import * as cache from 'react-stampit/utils/cache';

const id = cache.uniqueId();

export default React => {
  return cache.find(id) || cache.save(
    stampit(React, {
      // description object props
    }), id
  );
};
```

Does everyone agree on the cache method names?

**Comment by ericelliott** [comment]
:+1:

**Pull request merged**
